export const tikets = [
  {
    id: 1,
    input: "Москва",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-12-12",
    hotel: "Fortuna 4* Sharm",
    price: 100893,
    img: "image/2025-02-27 12.22.57.jpg",
  },
  {
    id: 2,
    input: "Москва",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-04-06",
    hotel: "VIVA SHARM HOTEL",
    price: 91219,
    img: "image/636652655492012888.jpg",
  },
  {
    id: 3,
    input: "Москва",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-05-05",
    hotel: "EMPIRE HOTEL AQUA PARK",
    price: 96686,
    img: "image/638211339572848374.jpg",
  },
  {
    id: 4,
    input: "Москва",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-04-11",
    hotel: "FALCON NAAMA STAR HOTEL",
    price: 99529,
    img: "image/636470474940462198.JPG",
  },
  {
    id: 5,
    input: "Москва",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-12-01",
    hotel: "FALCON HILLS HOTEL",
    price: 99529,
    img: "image/5.jpeg",
  },
  {
    id: 6,
    input: "Москва",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-08-07",
    hotel: "EDEN ROCK HOTEL",
    price: 99529,
    img: "image/6.jpeg",
  },
  {
    id: 7,
    input: "Москва",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-07-11",
    hotel: "SUNNY DAYS MIRETTE FAMILY AQUAPARK",
    price: 100951,
    img: "image/7.jpeg",
  },
  {
    id: 8,
    input: "Москва",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-06-24",
    hotel: "EL KHAN SHARM HOTEL",
    price: 100951,
    img: "image/8.jpeg",
  },
  {
    id: 9,
    input: "Москва",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-03-03",
    hotel: "DEXON ROMA HOTEL",
    price: 101036,
    img: "image/9.jpeg",
  },
  {
    id: 10,
    input: "Москва",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-08-09",
    hotel: "GRAND BLUE SAINT MARIA AQUA PARK",
    price: 102079,
    img: "image/10.jpeg",
  },
  {
    id: 11,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-12-12",
    hotel: "EMPIRE BEACH AQUA PARK",
    price: 103795,
    img: "image/11.jpeg",
  },
  {
    id: 12,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-05-07",
    hotel: "FARAANA HEIGHTS RESORT",
    price: 103795,
    img: "image/12.jpeg",
  },
  {
    id: 13,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-06-23",
    hotel: "EAGLES DOWN TOWN ZAHABIA RESORT",
    price: 104307,
    img: "image/13.jpeg",
  },
  {
    id: 14,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-04-04",
    hotel: "LA ROSA BOHO AQUA PARK HOTEL",
    price: 104819,
    img: "image/14.jpeg",
  },
  {
    id: 15,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-11-22",
    hotel: "SUN & SEA HOTEL",
    price: 105217,
    img: "image/15.jpeg",
  },
  {
    id: 16,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-01-07",
    hotel: "KING TUT AQUA PARK",
    price: 106639,
    img: "image/16.jpeg",
  },
  {
    id: 17,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-10-10",
    hotel: "EL KARMA AQUA BEACH RESORT",
    price: 108061,
    img: "image/17.jpeg",
  },
  {
    id: 18,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-12-01",
    hotel: "LA ROSA WAVES RESORT",
    price: 109483,
    img: "image/18.jpeg",
  },
  {
    id: 19,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Шарм-эш-Шейх ",
    transport: "Самолёт",
    date: "2025-04-14",
    hotel: "CORAL HILLS RESORT",
    price: 110905,
    img: "image/19.jpeg",
  },
  {
    id: 20,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-12-24",
    hotel: "MINAMARK RESORT & SPA",
    price: 110905,
    img: "image/20.jpeg",
  },
  {
    id: 21,
    input: "Москва",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-04-08",
    hotel: "HOTEL SAN ALEJANDRO",
    price: 228286,
    img: "image/21.jpeg",
  },
  {
    id: 22,
    input: "Москва",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-06-29",
    hotel: "GRAN CARIBE DEAUVILLE",
    price: 233121,
    img: "image/22.jpeg",
  },
  {
    id: 23,
    input: "Москва",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-05-05",
    hotel: "HOTEL VEDADO AZUL",
    price: 237102,
    img: "image/23.jpeg",
  },
  {
    id: 24,
    input: "Москва",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-12-10",
    hotel: "HOTEL TULIPAN",
    price: 241083,
    img: "image/24.jpeg",
  },
  {
    id: 25,
    input: "Москва",
    output: "Куба",
    sity: "Варадеро",
    transport: "Самолёт",
    date: "2025-10-12",
    hotel: "HOTEL KAWAMA (Ex.CLUB KAWAMA)",
    price: 242079,
    img: "image/25.jpeg",
  },
  {
    id: 26,
    input: "Санкт-Петербург",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-03-15",
    hotel: "STARFISH MONTE HABANA",
    price: 243927,
    img: "image/26.jpeg",
  },
  {
    id: 27,
    input: "Санкт-Петербург",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-11-11",
    hotel: "MEMORIES MIRAMAR HABANA",
    price: 248193,
    img: "image/27.jpeg",
  },
  {
    id: 28,
    input: "Санкт-Петербург",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-04-06",
    hotel: "HOTEL LIDO",
    price: 248193,
    img: "image/28.jpeg",
  },
  {
    id: 29,
    input: "Санкт-Петербург",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-03-03",
    hotel: "HOTEL CARIBBEAN",
    price: 248193,
    img: "image/29.jpeg",
  },
  {
    id: 30,
    input: "Санкт-Петербург",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-05-12",
    hotel: "GRAN CARIBE HOTEL PLAZA",
    price: 249046,
    img: "image/30.jpeg",
  },
  {
    id: 31,
    input: "Москва",
    output: "Россия",
    sity: "Калининград",
    transport: "Самолёт",
    date: "2025-09-25",
    hotel: "АПАРТ ОТЕЛЬ ПАЛЬМНИКЕН",
    price: 39398,
    img: "image/31.jpeg",
  },
  {
    id: 32,
    input: "Москва",
    output: "Россия",
    sity: "Калининград",
    transport: "Самолёт",
    date: "2025-06-08",
    hotel: "ОТЕЛЬ ПЕСОК И МОРЕ",
    price: 41628.13,
    img: "image/32.jpeg",
  },
  {
    id: 33,
    input: "Санкт-Петербург",
    output: "Россия",
    sity: "Калининград",
    transport: "Поезд",
    date: "2025-09-09",
    hotel: "АКВАМАРИН ПАРК",
    price: 59756,
    img: "image/33.jpeg",
  },
  {
    id: 34,
    input: "Москва",
    output: "Россия",
    sity: "Сочи",
    transport: "Самолёт",
    date: "2025-07-01",
    hotel: "ГОСТИНИЦА МАРО",
    price: 45092,
    img: "image/34.jpeg",
  },
  {
    id: 35,
    input: "Москва",
    output: "Россия",
    sity: "Сочи",
    transport: "Поезд",
    date: "2025-08-08",
    hotel: "КИВИ И ЦИТРУС",
    price: 42309,
    img: "image/35.jpeg",
  },
  {
    id: 36,
    input: "Санкт-Петербург",
    output: "Россия",
    sity: "Сочи",
    transport: "Самолёт",
    date: "2025-06-08",
    hotel: "ОТЕЛЬ GREEN ZONA",
    price: 44507,
    img: "image/36.jpeg",
  },
  {
    id: 37,
    input: "Санкт-Петербург",
    output: "Россия",
    sity: "Сочи",
    transport: "Самолёт",
    date: "2025-09-30",
    hotel: "ОТЕЛЬ КОМПАС",
    price: 46096,
    img: "image/37.jpeg",
  },
  {
    id: 38,
    input: "Санкт-Петербург",
    output: "Россия",
    sity: "Сочи",
    transport: "Поезд",
    date: "2025-08-09",
    hotel: "ГОСТЕВОЙ ДОМ ЭЛЬМИРА",
    price: 46598,
    img: "image/38.jpeg",
  },
  {
    id: 39,
    input: "Москва",
    output: "Россия",
    sity: "Санкт-Петербург",
    transport: "Поезд",
    date: "2025-09-09",
    hotel: "ОТЕЛЬ АРТ ДЕКО НЕВСКИЙ",
    price: 37413,
    img: "image/39.jpeg",
  },
  {
    id: 40,
    input: "Санкт-Петербург",
    output: "Россия",
    sity: "Архыз",
    transport: "Поезд",
    date: "2025-01-28",
    hotel: "КРАСНАЯ СКАЛА",
    price: 37840,
    img: "image/40.jpeg",
  },
];
