export const tikets = [
  {
    id: 1,
    input: "Москва",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-12-12",
    hotel: "Fortuna 4* Sharm",
    price: "100 893,36 ₽",
    img: "image/2025-02-27 12.22.57.jpg",
    count: 0,
  },
  {
    id: 2,
    input: "Москва",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-04-06",
    hotel: "VIVA SHARM HOTEL",
    price: "91 219,00 ₽",
    img: "image/636652655492012888.jpg",
    count: 0,
  },
  {
    id: 3,
    input: "Москва",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-05-05",
    hotel: "EMPIRE HOTEL AQUA PARK",
    price: "96 686,13 ₽",
    img: "image/638211339572848374.jpg",
    count: 0,
  },
  {
    id: 4,
    input: "Москва",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-04-11",
    hotel: "FALCON NAAMA STAR HOTEL",
    price: "99 529,95 ₽",
    img: "image/636470474940462198.JPG",
    count: 0,
  },
  {
    id: 5,
    input: "Москва",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-12-01",
    hotel: "FALCON HILLS HOTEL",
    price: "99 529,95 ₽",
    img: "image/5.jpeg",
    count: 0,
  },
  {
    id: 6,
    input: "Москва",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-08-07",
    hotel: "EDEN ROCK HOTEL",
    price: "99 529,95 ₽",
    img: "image/6.jpeg",
    count: 0,
  },
  {
    id: 7,
    input: "Москва",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-07-11",
    hotel: "SUNNY DAYS MIRETTE FAMILY AQUAPARK",
    price: "100 951,86 ₽",
    img: "image/7.jpeg",
    count: 0,
  },
  {
    id: 8,
    input: "Москва",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-06-24",
    hotel: "EL KHAN SHARM HOTEL",
    price: "100 951,86 ₽",
    img: "image/8.jpeg",
    count: 0,
  },
  {
    id: 9,
    input: "Москва",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-03-03",
    hotel: "DEXON ROMA HOTEL",
    price: "101 036,95 ₽",
    img: "image/9.jpeg",
    count: 0,
  },
  {
    id: 10,
    input: "Москва",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-08-09",
    hotel: "GRAND BLUE SAINT MARIA AQUA PARK",
    price: "102 079,14 ₽",
    img: "image/10.jpeg",
    count: 0,
  },
  {
    id: 11,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-12-12",
    hotel: "EMPIRE BEACH AQUA PARK",
    price: "103 795,68 ₽",
    img: "image/11.jpeg",
    count: 0,
  },
  {
    id: 12,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Шарм-эш-Шейх",
    transport: "Самолёт",
    date: "2025-05-07",
    hotel: "FARAANA HEIGHTS RESORT",
    price: "103 795,68 ₽",
    img: "image/12.jpeg",
    count: 0,
  },
  {
    id: 13,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-06-23",
    hotel: "EAGLES DOWN TOWN ZAHABIA RESORT",
    price: "104 307,16 ₽",
    img: "image/13.jpeg",
    count: 0,
  },
  {
    id: 14,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-04-04",
    hotel: "LA ROSA BOHO AQUA PARK HOTEL",
    price: "104 819,56 ₽",
    img: "image/14.jpeg",
    count: 0,
  },
  {
    id: 15,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-11-22",
    hotel: "SUN & SEA HOTEL",
    price: "105 217,59 ₽",
    img: "image/15.jpeg",
    count: 0,
  },
  {
    id: 16,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-01-07",
    hotel: "KING TUT AQUA PARK",
    price: "106 639,50 ₽",
    img: "image/16.jpeg",
    count: 0,
  },
  {
    id: 17,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-10-10",
    hotel: "EL KARMA AQUA BEACH RESORT",
    price: "108 061,41 ₽",
    img: "image/17.jpeg",
    count: 0,
  },
  {
    id: 18,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-12-01",
    hotel: "LA ROSA WAVES RESORT",
    price: "109 483,32 ₽",
    img: "image/18.jpeg",
    count: 0,
  },
  {
    id: 19,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Шарм-эш-Шейх ",
    transport: "Самолёт",
    date: "2025-04-14",
    hotel: "CORAL HILLS RESORT",
    price: "110 905,23 ₽",
    img: "image/19.jpeg",
    count: 0,
  },
  {
    id: 20,
    input: "Санкт-Петербург",
    output: "Египет",
    sity: "Хургада",
    transport: "Самолёт",
    date: "2025-12-24",
    hotel: "MINAMARK RESORT & SPA",
    price: "110 905,23 ₽",
    img: "image/20.jpeg",
    count: 0,
  },
  {
    id: 21,
    input: "Москва",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-04-08",
    hotel: "HOTEL SAN ALEJANDRO",
    price: "228 286,52 ₽",
    img: "image/21.jpeg",
    count: 0,
  },
  {
    id: 22,
    input: "Москва",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-06-29",
    hotel: "GRAN CARIBE DEAUVILLE",
    price: "233 121,38 ₽",
    img: "image/22.jpeg",
    count: 0,
  },
  {
    id: 23,
    input: "Москва",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-05-05",
    hotel: "HOTEL VEDADO AZUL",
    price: "237 102,55 ₽",
    img: "image/23.jpeg",
    count: 0,
  },
  {
    id: 24,
    input: "Москва",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-12-10",
    hotel: "HOTEL TULIPAN",
    price: "241 083,71 ₽",
    img: "image/24.jpeg",
    count: 0,
  },
  {
    id: 25,
    input: "Москва",
    output: "Куба",
    sity: "Варадеро",
    transport: "Самолёт",
    date: "2025-10-12",
    hotel: "HOTEL KAWAMA (Ex.CLUB KAWAMA)",
    price: "242 079,23 ₽",
    img: "image/25.jpeg",
    count: 0,
  },
  {
    id: 26,
    input: "Санкт-Петербург",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-03-15",
    hotel: "STARFISH MONTE HABANA",
    price: "243 927,53 ₽",
    img: "image/26.jpeg",
    count: 0,
  },
  {
    id: 27,
    input: "Санкт-Петербург",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-11-11",
    hotel: "MEMORIES MIRAMAR HABANA",
    price: "248 193,26 ₽",
    img: "image/27.jpeg",
    count: 0,
  },
  {
    id: 28,
    input: "Санкт-Петербург",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-04-06",
    hotel: "HOTEL LIDO",
    price: "248 193,26 ₽",
    img: "image/28.jpeg",
    count: 0,
  },
  {
    id: 29,
    input: "Санкт-Петербург",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-03-03",
    hotel: "HOTEL CARIBBEAN",
    price: "248 193,26 ₽",
    img: "image/29.jpeg",
    count: 0,
  },
  {
    id: 30,
    input: "Санкт-Петербург",
    output: "Куба",
    sity: "Гавана",
    transport: "Самолёт",
    date: "2025-05-12",
    hotel: "GRAN CARIBE HOTEL PLAZA",
    price: "249 046,04 ₽",
    img: "image/30.jpeg",
    count: 0,
  },
  {
    id: 31,
    input: "Москва",
    output: "Россия",
    sity: "Калининград",
    transport: "Самолёт",
    date: "2025-09-25",
    hotel: "АПАРТ ОТЕЛЬ ПАЛЬМНИКЕН",
    price: "39 398,70 ₽",
    img: "image/31.jpeg",
    count: 0,
  },
  {
    id: 32,
    input: "Москва",
    output: "Россия",
    sity: "Калининград",
    transport: "Самолёт",
    date: "2025-06-08",
    hotel: "ОТЕЛЬ ПЕСОК И МОРЕ",
    price: "41 628,13 ₽",
    img: "image/32.jpeg",
    count: 0,
  },
  {
    id: 33,
    input: "Санкт-Петербург",
    output: "Россия",
    sity: "Калининград",
    transport: "Поезд",
    date: "2025-09-09",
    hotel: "АКВАМАРИН ПАРК",
    price: "59 756,52 ₽",
    img: "image/33.jpeg",
    count: 0,
  },
  {
    id: 34,
    input: "Москва",
    output: "Россия",
    sity: "Сочи",
    transport: "Самолёт",
    date: "2025-07-01",
    hotel: "ГОСТИНИЦА МАРО",
    price: "45 092,91 ₽",
    img: "image/34.jpeg",
    count: 0,
  },
  {
    id: 35,
    input: "Москва",
    output: "Россия",
    sity: "Сочи",
    transport: "Поезд",
    date: "2025-08-08",
    hotel: "КИВИ И ЦИТРУС",
    price: "42 309,38 ₽",
    img: "image/35.jpeg",
    count: 0,
  },
  {
    id: 36,
    input: "Санкт-Петербург",
    output: "Россия",
    sity: "Сочи",
    transport: "Самолёт",
    date: "2025-06-08",
    hotel: "ОТЕЛЬ GREEN ZONA",
    price: "44 507,46 ₽",
    img: "image/36.jpeg",
    count: 0,
  },
  {
    id: 37,
    input: "Санкт-Петербург",
    output: "Россия",
    sity: "Сочи",
    transport: "Самолёт",
    date: "2025-09-30",
    hotel: "ОТЕЛЬ КОМПАС",
    price: "46 096,54 ₽",
    img: "image/37.jpeg",
    count: 0,
  },
  {
    id: 38,
    input: "Санкт-Петербург",
    output: "Россия",
    sity: "Сочи",
    transport: "Поезд",
    date: "2025-08-09",
    hotel: "ГОСТЕВОЙ ДОМ ЭЛЬМИРА",
    price: "46 598,36 ₽",
    img: "image/38.jpeg",
    count: 0,
  },
  {
    id: 39,
    input: "Москва",
    output: "Россия",
    sity: "Санкт-Петербург",
    transport: "Поезд",
    date: "2025-09-09",
    hotel: "ОТЕЛЬ АРТ ДЕКО НЕВСКИЙ",
    price: "37 413,90 ₽",
    img: "image/39.jpeg",
    count: 0,
  },
  {
    id: 40,
    input: "Санкт-Петербург",
    output: "Россия",
    sity: "Архыз",
    transport: "Поезд",
    date: "2025-01-28",
    hotel: "КРАСНАЯ СКАЛА",
    price: "37 840,36 ₽",
    img: "image/40.jpeg",
    count: 0,
  },
];
